// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { alignBottom } from "./alignBottom.js";
import { alignCenter } from "./alignCenter.js";
import { alignCenterX } from "./alignCenterX.js";
import { alignCenterY } from "./alignCenterY.js";
import { alignLeft } from "./alignLeft.js";
import { alignRight } from "./alignRight.js";
import { alignTop } from "./alignTop.js";
import { area } from "./area.js";
import { bottom } from "./bottom.js";
import { centerX } from "./centerX.js";
import { centerY } from "./centerY.js";
import { clamp } from "./clamp.js";
import { contain } from "./contain.js";
import { contains } from "./contains.js";
import { cover } from "./cover.js";
import { distance } from "./distance.js";
import { dropBottomPct } from "./dropBottomPct.js";
import { dropBottomPx } from "./dropBottomPx.js";
import { dropLeftPct } from "./dropLeftPct.js";
import { dropLeftPx } from "./dropLeftPx.js";
import { dropRightPct } from "./dropRightPct.js";
import { dropRightPx } from "./dropRightPx.js";
import { dropTopPct } from "./dropTopPct.js";
import { dropTopPx } from "./dropTopPx.js";
import { expand } from "./expand.js";
import { expandX } from "./expandX.js";
import { expandY } from "./expandY.js";
import { fromDOMRect } from "./fromDOMRect.js";
import { fromEdges } from "./fromEdges.js";
import { fromElement } from "./fromElement.js";
import { fromWindow } from "./fromWindow.js";
import { height } from "./height.js";
import { intersection } from "./intersection.js";
import { intersects } from "./intersects.js";
import { isEmpty } from "./isEmpty.js";
import { isEqual } from "./isEqual.js";
import { isOrigin } from "./isOrigin.js";
import { left } from "./left.js";
import { map } from "./map.js";
import { merge } from "./merge.js";
import { moveBottomTo } from "./moveBottomTo.js";
import { moveLeftTo } from "./moveLeftTo.js";
import { moveRightTo } from "./moveRightTo.js";
import { moveTopTo } from "./moveTopTo.js";
import { normalize } from "./normalize.js";
import { origin } from "./origin.js";
import { placeAboveBy } from "./placeAboveBy.js";
import { placeBelowBy } from "./placeBelowBy.js";
import { placeLeftOfBy } from "./placeLeftOfBy.js";
import { placeRightOfBy } from "./placeRightOfBy.js";
import { Rect } from "./types.js";
import { right } from "./right.js";
import { scale } from "./scale.js";
import { scaleX } from "./scaleX.js";
import { scaleY } from "./scaleY.js";
import { setBottom } from "./setBottom.js";
import { setCenter } from "./setCenter.js";
import { setCenterX } from "./setCenterX.js";
import { setCenterY } from "./setCenterY.js";
import { setHeight } from "./setHeight.js";
import { setLeft } from "./setLeft.js";
import { setRight } from "./setRight.js";
import { setTop } from "./setTop.js";
import { setWidth } from "./setWidth.js";
import { shrink } from "./shrink.js";
import { shrinkX } from "./shrinkX.js";
import { shrinkY } from "./shrinkY.js";
import { snapAbove } from "./snapAbove.js";
import { snapBelow } from "./snapBelow.js";
import { snapLeftOf } from "./snapLeftOf.js";
import { snapRightOf } from "./snapRightOf.js";
import { takeBottomPct } from "./takeBottomPct.js";
import { takeBottomPx } from "./takeBottomPx.js";
import { takeLeftPct } from "./takeLeftPct.js";
import { takeLeftPx } from "./takeLeftPx.js";
import { takeRightPct } from "./takeRightPct.js";
import { takeRightPx } from "./takeRightPx.js";
import { takeTopPct } from "./takeTopPct.js";
import { takeTopPx } from "./takeTopPx.js";
import { top } from "./top.js";
import { transform } from "./transform.js";
import { translate } from "./translate.js";
import { translateX } from "./translateX.js";
import { translateY } from "./translateY.js";
import { union } from "./union.js";
import { width } from "./width.js";

declare namespace Rect {
    export {
        alignBottom,
        alignCenter,
        alignCenterX,
        alignCenterY,
        alignLeft,
        alignRight,
        alignTop,
        area,
        bottom,
        centerX,
        centerY,
        clamp,
        contain,
        contains,
        cover,
        distance,
        dropBottomPct,
        dropBottomPx,
        dropLeftPct,
        dropLeftPx,
        dropRightPct,
        dropRightPx,
        dropTopPct,
        dropTopPx,
        expand,
        expandX,
        expandY,
        fromDOMRect,
        fromEdges,
        fromElement,
        fromWindow,
        height,
        intersection,
        intersects,
        isEmpty,
        isEqual,
        isOrigin,
        left,
        map,
        merge,
        moveBottomTo,
        moveLeftTo,
        moveRightTo,
        moveTopTo,
        normalize,
        origin,
        placeAboveBy,
        placeBelowBy,
        placeLeftOfBy,
        placeRightOfBy,
        right,
        scale,
        scaleX,
        scaleY,
        setBottom,
        setCenter,
        setCenterX,
        setCenterY,
        setHeight,
        setLeft,
        setRight,
        setTop,
        setWidth,
        shrink,
        shrinkX,
        shrinkY,
        snapAbove,
        snapBelow,
        snapLeftOf,
        snapRightOf,
        takeBottomPct,
        takeBottomPx,
        takeLeftPct,
        takeLeftPx,
        takeRightPct,
        takeRightPx,
        takeTopPct,
        takeTopPx,
        top,
        transform,
        translate,
        translateX,
        translateY,
        union,
        width,
    }
}

export {
    Rect,
}
