import { defineConfig } from "vitepress"
import { groupIconMdPlugin, groupIconVitePlugin } from "vitepress-plugin-group-icons"

export default defineConfig({
    base: "/geometry/",
    description: "Functional geometry utilities.",
    title: "geometry",
    markdown: {
        theme: {
            dark: "catppuccin-macchiato",
            light: "github-light-default",
        },
        config(md) {
            md.use(groupIconMdPlugin)
        },
    },
    themeConfig: {
        aside: false,
        outline: "deep",
        docFooter: {
            next: false,
            prev: false,
        },
        search: {
            provider: "local",
        },
        sidebar: [
            {
                base: "/Rect/",
                text: "Rect",
                items: [
                    { link: "alignBottom", text: "alignBottom" },
                    { link: "alignCenter", text: "alignCenter" },
                    { link: "alignCenterX", text: "alignCenterX" },
                    { link: "alignCenterY", text: "alignCenterY" },
                    { link: "alignLeft", text: "alignLeft" },
                    { link: "alignRight", text: "alignRight" },
                    { link: "alignTop", text: "alignTop" },
                    { link: "area", text: "area" },
                    { link: "bottom", text: "bottom" },
                    { link: "centerX", text: "centerX" },
                    { link: "centerY", text: "centerY" },
                    { link: "clamp", text: "clamp" },
                    { link: "contain", text: "contain" },
                    { link: "contains", text: "contains" },
                    { link: "cover", text: "cover" },
                    { link: "distance", text: "distance" },
                    { link: "dropBottomPct", text: "dropBottomPct" },
                    { link: "dropBottomPx", text: "dropBottomPx" },
                    { link: "dropLeftPct", text: "dropLeftPct" },
                    { link: "dropLeftPx", text: "dropLeftPx" },
                    { link: "dropRightPct", text: "dropRightPct" },
                    { link: "dropRightPx", text: "dropRightPx" },
                    { link: "dropTopPct", text: "dropTopPct" },
                    { link: "dropTopPx", text: "dropTopPx" },
                    { link: "expand", text: "expand" },
                    { link: "expandX", text: "expandX" },
                    { link: "expandY", text: "expandY" },
                    { link: "fromDOMRect", text: "fromDOMRect" },
                    { link: "fromEdges", text: "fromEdges" },
                    { link: "fromElement", text: "fromElement" },
                    { link: "fromWindow", text: "fromWindow" },
                    { link: "height", text: "height" },
                    { link: "intersection", text: "intersection" },
                    { link: "intersects", text: "intersects" },
                    { link: "isEmpty", text: "isEmpty" },
                    { link: "isEqual", text: "isEqual" },
                    { link: "isOrigin", text: "isOrigin" },
                    { link: "left", text: "left" },
                    { link: "map", text: "map" },
                    { link: "merge", text: "merge" },
                    { link: "moveBottomTo", text: "moveBottomTo" },
                    { link: "moveLeftTo", text: "moveLeftTo" },
                    { link: "moveRightTo", text: "moveRightTo" },
                    { link: "moveTopTo", text: "moveTopTo" },
                    { link: "normalize", text: "normalize" },
                    { link: "origin", text: "origin" },
                    { link: "placeAboveBy", text: "placeAboveBy" },
                    { link: "placeBelowBy", text: "placeBelowBy" },
                    { link: "placeLeftOfBy", text: "placeLeftOfBy" },
                    { link: "placeRightOfBy", text: "placeRightOfBy" },
                    { link: "right", text: "right" },
                    { link: "scale", text: "scale" },
                    { link: "scaleX", text: "scaleX" },
                    { link: "scaleY", text: "scaleY" },
                    { link: "setBottom", text: "setBottom" },
                    { link: "setCenter", text: "setCenter" },
                    { link: "setCenterX", text: "setCenterX" },
                    { link: "setCenterY", text: "setCenterY" },
                    { link: "setHeight", text: "setHeight" },
                    { link: "setLeft", text: "setLeft" },
                    { link: "setRight", text: "setRight" },
                    { link: "setTop", text: "setTop" },
                    { link: "setWidth", text: "setWidth" },
                    { link: "shrink", text: "shrink" },
                    { link: "shrinkX", text: "shrinkX" },
                    { link: "shrinkY", text: "shrinkY" },
                    { link: "snapAbove", text: "snapAbove" },
                    { link: "snapBelow", text: "snapBelow" },
                    { link: "snapLeftOf", text: "snapLeftOf" },
                    { link: "snapRightOf", text: "snapRightOf" },
                    { link: "takeBottomPct", text: "takeBottomPct" },
                    { link: "takeBottomPx", text: "takeBottomPx" },
                    { link: "takeLeftPct", text: "takeLeftPct" },
                    { link: "takeLeftPx", text: "takeLeftPx" },
                    { link: "takeRightPct", text: "takeRightPct" },
                    { link: "takeRightPx", text: "takeRightPx" },
                    { link: "takeTopPct", text: "takeTopPct" },
                    { link: "top", text: "top" },
                    { link: "transform", text: "transform" },
                    { link: "translate", text: "translate" },
                    { link: "translateX", text: "translateX" },
                    { link: "translateY", text: "translateY" },
                    { link: "union", text: "union" },
                    { link: "width", text: "width" },
                ],
            },
        ],
        socialLinks: [
            { icon: "github", link: "https://github.com/MichaelOstermann/geometry" },
        ],
    },
    vite: {
        plugins: [
            groupIconVitePlugin(),
        ],
    },
})
